### ISSUE TITLE
degenes_Hunter.R fails to write html report

### ISSUE THREAD

**Issue by seoanezonjic** [seoanezonjic/DEgenesHunter#11]
The following error is given by degenes_Hunter.R:
`Error: The directory 'DEGenesHunter_results') does not not exist.`

When it is executed as
``` bash
head -n 500 filtered_count_data.txt > sample_counts.txt

TARGET_FILE=./target.txt
controls=`grep 'Ctrl' $TARGET_FILE | cut -f 1 | tr "\n" ","`
controls=${controls%?}
treatments=`grep 'Treat' $TARGET_FILE | cut -f 1 | tr "\n" ","`
treatments=${treatments%?}

output=DEGenesHunter_results
mkdir -p $output
degenes_Hunter.R -i sample_counts.txt -C $controls -T $treatments -o $output -m 'DE'
```
The error causing code:
``` R
rmarkdown::render(file.path(main_path_script, 'templates', 'main_report.Rmd'),
                  output_file = outf, intermediates_dir = opt$output_files)
```

**Comment by jimrperkins** [comment]
Fixed, was due to an error whereby file.path() was unable to detect the absolute path of the outf variable. Code for this line changed back to the version.

**Comment by jimrperkins** [comment]
Fixed, was due to an error whereby file.path() was unable to detect the absolute path of the outf variable. Code for this line changed back to the version.
