### ISSUE TITLE
functional_report throws error in gsea chunk when object is empty

### ISSUE THREAD

**Issue by jimrperkins** [seoanezonjic/DEgenesHunter#12]
Following text given:

Quitting from lines 145-308 (functional_report.Rmd) 
Error in which(set@result$p.adjust <= set@pvalueCutoff) : 
  no slot of name "pvalueCutoff" for this object of class "gseaResult"

**Comment by fmjabato** [comment]
Solved, problem based on "check_results" function which access to slots without check if it existes [slots(enrichResult) != sltos(gseaResults)]
