### ISSUE TITLE
Functional hunter doesn't work

### ISSUE THREAD

**Issue by JoseCorCab** [seoanezonjic/DEgenesHunter#14]
Functional Hunter is not working. In case of no-wgcna execution, it breaks during markdown template execution giving this error 

`Quitting from lines 354-419 (functional_report.Rmd) 
Error in fc_readable(x, foldChange) : objeto 'geneList' no encontrado
Calls: <Anonymous> ... cnetplot -> cnetplot -> cnetplot.enrichResult -> fc_readable
`

When launching wgcna it return this error: 
`Error in download.KEGG.Path(species) : 
  'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'...
Calls: lapply ... prepare_KEGG -> download_KEGG -> download.KEGG.Path`

It seems that the program is not recognicing the species name

Here you have a test dataset with both cases: https://www.dropbox.com/s/magsd6yjgffv52y/issue_test.zip?dl=0

**Comment by fmjabato** [comment]
About geneList bug, I see that you are not running GSEA enrichments and "geneList" is generated only for GSEA modules. I'll check the report, thank you for info.

About KEGG error, I need, at least, "control_treatment.txt" to use your test data and I assume that you're using Git biomaRt_organism_table.txt file and not a custom one.

Please, give me the control_treatment file to reproduce your error

**Comment by fmjabato** [comment]
Okey, your reported bugs have been fixed:

1. "geneList" bug consist on report assuming that geneList always exists, but only is calculated when GSEA module has been launched. Now, geneList is always calculated
2. KEGG errors occurs for "clusters" mode and consists on an undesired launch of "remote" mode even if remote mode has not been requested.

After that, I close this issue
