### ISSUE TITLE
Improve library filtering

### ISSUE THREAD

**Issue by seoanezonjic** [seoanezonjic/DEgenesHunter#4]
The following code filter the counts without take into account the treatment and control tags:
```R
 keep_cmp <- rowSums(edgeR::cpm(raw) > opt$reads) >= opt$minlibraries # genes with cpm greater than --reads value for at least --minlibrariess samples
 raw_filter <- raw[keep_cmp,] # Filter out count data frame
```
For example, a gene could be fully represed in treatment and in control show all libraries can express this gene. But a gene that has expression in one control library and in one treatment library (in a 3 vs 3 comparison) makes non sense. Think that this filter should be check that at least one tag (control or treatment) has the minlibraries.

**Comment by jimrperkins** [comment]
DEGeneshuner now now looks at control and treatment files separately when testing how many samples have a minimum number of reads.

**Comment by jimrperkins** [comment]
DEGeneshuner now now looks at control and treatment files separately when testing how many samples have a minimum number of reads.
