### ISSUE TITLE
Path error for Functional Hunter organism_table.txt file (no debug mode)

### ISSUE THREAD

**Issue by ElenaRojano** [seoanezonjic/DEgenesHunter#42]
Error:
In file(file, "rt") :
  cannot open file '/mnt/home/soft/soft_bio_267/programs/x86_64/DEgenesHunter/inst/scripts/../../R/organism_table.txt': No such file or directory

If this can help you: exploring functional_Hunter.R, in line 17:

> organisms_table_file <- file.path(root_path, "R", "organism_table.txt")

I guess it should be:

> organisms_table_file <- file.path(root_path, "external_data", "organism_table.txt")

**Comment by fmjabato** [comment]
This problem was solved several commits ago. Update your current package version
